name: Deploy Backend

on:
  push:
    branches:
      - 'master'
    paths:
      - 'backend/**'

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-privet-key: ${{ secrets.PA_SSH_PRIVATE_KEY}}

      - name: Add PythonAnywhere to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.PA_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy backend using rsync
        env:
          PA_USERNAME: ${{secrets.PA_USERNAME}}
          PA_HOST: ${{secrets.PA_HOST}}
          PA_TARGET_DIR: ${{secrets.PA_TARGET_DIR}}
        run: |
          echo "Syncing ./backend/ directory to PythonAnywhere target: $PA_TARGET_DIR"
          rsync -av --delete ./backend/ "${PA_USERNAME}@${PA_HOST}:${PA_TARGET_DIR}/"