name: Deploy Backend

on:
  push:
    branches:
      - 'master'
    paths:
      - 'backend/**'

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to PythonAnyWhere
        run: |
          echo 'Testing the deployment workflow'